version = 0.1
[default.deploy.parameters]
stack_name = "lambda-authorizer-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-0unj1t2uz9ks"
s3_prefix = "lambda-authorizer-example"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
